name: Trigger pre merge tests
on:
  # Enable manually triggering a test run using GitHub UI
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
jobs:
  trigger-circleci:
    name: Trigger CircleCI
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: timeedit/tesafe-action@v1.2.1
        with:
          export_mode: env
          safe_token: ${{ secrets.SAFE_TOKEN }}
          safe_context: circleci_assisted_engine
          variables: |
            CCI_TOKEN: /circle_ci_api_token,
      - name: Trigger circleci test workflow
        id: pre-merge
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.7
